### ISSUE TITLE
ClusterIssuer resource was applied sooner than CertManager installed

### ISSUE THREAD

**Issue by laszlocph** [gimlet-io/gimlet-stack-reference#23]
Need to define multiple kustomizations with depends-on

**Comment by laszlocph** [comment]
ClusterIssuer/letsencrypt dry-run failed, error: no matches for kind \"ClusterIssuer\

**Comment by laszlocph** [comment]
`gimlet gitops bootstrap` must bootstrap an other kustomization that applies the `dependencies` folder, and the current kustomization to depend on this new one.

Here is an example

```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gitops-repo-laszlocph-gitops-deleteme306-infra-dependencies
  namespace: flux-system
spec:
  interval: 24h0m0s
  path: ./dependencies
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-repo-laszlocph-gitops-deleteme306-infra
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gitops-repo-laszlocph-gitops-deleteme306-infra
  namespace: flux-system
spec:
  interval: 24h0m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-repo-laszlocph-gitops-deleteme306-infra
  validation: client
  dependsOn:
    - name: gitops-repo-laszlocph-gitops-deleteme306-infra-dependencies

```
